name: 'Build APES solver'
description: 'Run the bin/waf command in the repo directory'
inputs:
  waf-args:
    description: 'Arguments to the bin/waf command'
    required: true
    default: 'configure build'
  path:
    description: 'Path in the project in which waf is to be run'
    required: true
    default: '.'
  obtain:
    description: 'Path to copy back after building'
    required: true
    default: 'build'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.waf-args }}
    - ${{ inputs.path }}
    - ${{ inputs.obtain }}
