# Increment version on merge to master from pull request
name: Bump version
on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  tag:
    #if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        node-version:
          - 12

    steps:
    - name: Bump version and push tag
      id: tagbump
      uses: phish108/autotag-action@v1.1.64
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        dry-run: true
        with-v: true
    - name: Control output
      run: |
        echo "New tag: ${{ steps.tagbump.outputs.new-tag }}"

