name: Bump version
# Increment version on merge to master from pull request
on:
  workflow_dispatch:
  pull_request:
    #types:
    #  - closed
    branches:
      - main

jobs:
  autotag:
    #if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      new-tag: ${{ steps.tagbump.outputs.new-tag }}
      updated: ${{ steps.tagbump.outputs.new-tag != steps.tagbump.outputs.tag }}
    strategy:
      matrix:
        node-version:
          - 12

    steps:
    - name: Bump version and push tag
      id: tagbump
      uses: phish108/autotag-action@v1.1.64
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        dry-run: true
        with-v: true

  movetags:
    needs: autotag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Get semvers and update MAJOR and MINOR tags
      run: |
        FULL=${{ needs.autotag.outputs.new-tag }}
        MINOR=${FULL%.*}
        MAJOR=${MINOR%%.*}
        echo "tags to move: $MINOR, $MAJOR"
        echo "git config --global user.name 'github-actions[bot]'"
        echo "git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'"
        echo "git tag -fa "${MAJOR}" -m 'Major release'"
        echo "git push origin "${MAJOR}" --force"
        echo "git tag -fa "${MINOR}" -m 'Minor release'"
        echo "git push origin "${MINOR}" --force"
