name: Bump version
# Increment version on merge to master from pull request
on:
  workflow_dispatch:
  pull_request:
    #types:
    #  - closed
    branches:
      - main

jobs:
  tag:
    #if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        node-version:
          - 12

    steps:
    - name: Bump version and push tag
      id: tagbump
      uses: phish108/autotag-action@v1.1.64
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        dry-run: true
        with-v: true
    - name: Control output
      run: |
        echo "New tag: ${{ steps.tagbump.outputs.new-tag }}"
    - name: Get semvers and update MAJOR and MINOR tags
      run: |
        FULL=${{ steps.tagbump.outputs.new-tag }}
        MINOR=${FULL%.*}
        MAJOR=${MINOR%%.*}
        echo "tags to move: $MINOR, $MAJOR"
